// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <RcppEigen.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>& Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// b_ism_wrapper
Rcpp::List b_ism_wrapper(Rcpp::NumericMatrix data, bool include_constant, bool tfe, bool ife, bool iis, bool sis, int y_index, int i_index, int t_index, long Ndraw, long Nburn, std::string b_prior, double lambda_b, double c0, double C0, bool geweke, double tau, double va, double vb, std::string model_sel_optimization);
RcppExport SEXP _BISAM_b_ism_wrapper(SEXP dataSEXP, SEXP include_constantSEXP, SEXP tfeSEXP, SEXP ifeSEXP, SEXP iisSEXP, SEXP sisSEXP, SEXP y_indexSEXP, SEXP i_indexSEXP, SEXP t_indexSEXP, SEXP NdrawSEXP, SEXP NburnSEXP, SEXP b_priorSEXP, SEXP lambda_bSEXP, SEXP c0SEXP, SEXP C0SEXP, SEXP gewekeSEXP, SEXP tauSEXP, SEXP vaSEXP, SEXP vbSEXP, SEXP model_sel_optimizationSEXP) {
    BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter<Rcpp::NumericMatrix>::type data(dataSEXP);
    Rcpp::traits::input_parameter<bool>::type include_constant(include_constantSEXP);
    Rcpp::traits::input_parameter<bool>::type tfe(tfeSEXP);
    Rcpp::traits::input_parameter<bool>::type ife(ifeSEXP);
    Rcpp::traits::input_parameter<bool>::type iis(iisSEXP);
    Rcpp::traits::input_parameter<bool>::type sis(sisSEXP);
    Rcpp::traits::input_parameter<int>::type y_index(y_indexSEXP);
    Rcpp::traits::input_parameter<int>::type i_index(i_indexSEXP);
    Rcpp::traits::input_parameter<int>::type t_index(t_indexSEXP);
    Rcpp::traits::input_parameter<long>::type Ndraw(NdrawSEXP);
    Rcpp::traits::input_parameter<long>::type Nburn(NburnSEXP);
    Rcpp::traits::input_parameter<std::string>::type b_prior(b_priorSEXP);
    Rcpp::traits::input_parameter<double>::type lambda_b(lambda_bSEXP);
    Rcpp::traits::input_parameter<double>::type c0(c0SEXP);
    Rcpp::traits::input_parameter<double>::type C0(C0SEXP);
    Rcpp::traits::input_parameter<bool>::type geweke(gewekeSEXP);
    Rcpp::traits::input_parameter<double>::type tau(tauSEXP);
    Rcpp::traits::input_parameter<double>::type va(vaSEXP);
    Rcpp::traits::input_parameter<double>::type vb(vbSEXP);
    Rcpp::traits::input_parameter<std::string>::type model_sel_optimization(model_sel_optimizationSEXP);
    rcpp_result_gen = Rcpp::wrap(b_ism_wrapper(data, include_constant, tfe, ife, iis, sis, y_index, i_index, t_index, Ndraw, Nburn, b_prior, lambda_b, c0, C0, geweke, tau, va, vb, model_sel_optimization));
    return rcpp_result_gen;
    END_RCPP
}
// rnlp_wrapper
Rcpp::NumericVector rnlp_wrapper(int niter, int burnin, int thinning, Rcpp::NumericVector y, Rcpp::IntegerMatrix x, double tau, double a_phi, double b_phi, int prior, Rcpp::NumericVector thini, double phiini);
RcppExport SEXP _BISAM_rnlp_wrapper(SEXP niterSEXP, SEXP burninSEXP, SEXP thinningSEXP, SEXP ySEXP, SEXP xSEXP, SEXP tauSEXP, SEXP a_phiSEXP, SEXP b_phiSEXP, SEXP priorSEXP, SEXP thiniSEXP, SEXP phiiniSEXP) {
    BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter<int>::type niter(niterSEXP);
    Rcpp::traits::input_parameter<int>::type burnin(burninSEXP);
    Rcpp::traits::input_parameter<int>::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter<Rcpp::NumericVector>::type y(ySEXP);
    Rcpp::traits::input_parameter<Rcpp::IntegerMatrix>::type x(xSEXP);
    Rcpp::traits::input_parameter<double>::type tau(tauSEXP);
    Rcpp::traits::input_parameter<double>::type a_phi(a_phiSEXP);
    Rcpp::traits::input_parameter<double>::type b_phi(b_phiSEXP);
    Rcpp::traits::input_parameter<int>::type prior(priorSEXP);
    Rcpp::traits::input_parameter<Rcpp::NumericVector>::type thini(thiniSEXP);
    Rcpp::traits::input_parameter<double>::type phiini(phiiniSEXP);
    rcpp_result_gen = Rcpp::wrap(rnlp_wrapper(niter, burnin, thinning, y, x, tau, a_phi, b_phi, prior, thini, phiini));
    return rcpp_result_gen;
    END_RCPP
}
// model_selection_wrapper
Rcpp::IntegerVector model_selection_wrapper(Rcpp::NumericVector y, Rcpp::IntegerMatrix x, int n_iter, Rcpp::List priorCoef, Rcpp::List priorDelta, double phi, Rcpp::IntegerVector w_i, int n_observations, int n_timeperiods, std::string optimization_methode, bool standardize);
RcppExport SEXP _BISAM_model_selection_wrapper(SEXP ySEXP, SEXP xSEXP, SEXP n_iterSEXP, SEXP priorCoefSEXP, SEXP priorDeltaSEXP, SEXP phiSEXP, SEXP w_iSEXP, SEXP n_observationsSEXP, SEXP n_timeperiodsSEXP, SEXP optimization_methodeSEXP, SEXP standardizeSEXP) {
    BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter<Rcpp::NumericVector>::type y(ySEXP);
    Rcpp::traits::input_parameter<Rcpp::IntegerMatrix>::type x(xSEXP);
    Rcpp::traits::input_parameter<int>::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter<Rcpp::List>::type priorCoef(priorCoefSEXP);
    Rcpp::traits::input_parameter<Rcpp::List>::type priorDelta(priorDeltaSEXP);
    Rcpp::traits::input_parameter<double>::type phi(phiSEXP);
    Rcpp::traits::input_parameter<Rcpp::IntegerVector>::type w_i(w_iSEXP);
    Rcpp::traits::input_parameter<int>::type n_observations(n_observationsSEXP);
    Rcpp::traits::input_parameter<int>::type n_timeperiods(n_timeperiodsSEXP);
    Rcpp::traits::input_parameter<std::string>::type optimization_methode(optimization_methodeSEXP);
    Rcpp::traits::input_parameter<bool>::type standardize(standardizeSEXP);
    rcpp_result_gen = Rcpp::wrap(model_selection_wrapper(y, x, n_iter, priorCoef, priorDelta, phi, w_i, n_observations, n_timeperiods, optimization_methode, standardize));
    return rcpp_result_gen;
    END_RCPP
}
// imomprior
List imomprior(double tau, double tau_adj);
RcppExport SEXP _BISAM_imomprior(SEXP tauSEXP, SEXP tau_adjSEXP) {
    BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter<double>::type tau(tauSEXP);
    Rcpp::traits::input_parameter<double>::type tau_adj(tau_adjSEXP);
    rcpp_result_gen = Rcpp::wrap(imomprior(tau, tau_adj));
    return rcpp_result_gen;
    END_RCPP
}
// modelbbprior
List modelbbprior(double alpha_p, double beta_p);
RcppExport SEXP _BISAM_modelbbprior(SEXP alpha_pSEXP, SEXP beta_pSEXP) {
    BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter<double>::type alpha_p(alpha_pSEXP);
    Rcpp::traits::input_parameter<double>::type beta_p(beta_pSEXP);
    rcpp_result_gen = Rcpp::wrap(modelbbprior(alpha_p, beta_p));
    return rcpp_result_gen;
    END_RCPP
}
// igprior
List igprior(double alpha, double lambda);
RcppExport SEXP _BISAM_igprior(SEXP alphaSEXP, SEXP lambdaSEXP) {
    BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter<double>::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter<double>::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(igprior(alpha, lambda));
    return rcpp_result_gen;
    END_RCPP
}
// momprior
List momprior(double tau, double tau_adj, double r);
RcppExport SEXP _BISAM_momprior(SEXP tauSEXP, SEXP tau_adjSEXP, SEXP rSEXP) {
    BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter<double>::type tau(tauSEXP);
    Rcpp::traits::input_parameter<double>::type tau_adj(tau_adjSEXP);
    Rcpp::traits::input_parameter<double>::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(momprior(tau, tau_adj, r));
    return rcpp_result_gen;
    END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BISAM_b_ism_wrapper", (DL_FUNC)&_BISAM_b_ism_wrapper, 20},
    {"_BISAM_rnlp_wrapper", (DL_FUNC)&_BISAM_rnlp_wrapper, 11},
    {"_BISAM_model_selection_wrapper", (DL_FUNC)&_BISAM_model_selection_wrapper, 11},
    {"_BISAM_imomprior", (DL_FUNC)&_BISAM_imomprior, 2},
    {"_BISAM_modelbbprior", (DL_FUNC)&_BISAM_modelbbprior, 2},
    {"_BISAM_igprior", (DL_FUNC)&_BISAM_igprior, 2},
    {"_BISAM_momprior", (DL_FUNC)&_BISAM_momprior, 3},
    {NULL, NULL, 0}};

RcppExport void R_init_BISAM(DllInfo* dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
