// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// b_ism_wrapper
Rcpp::List b_ism_wrapper(Rcpp::NumericMatrix data, bool include_constant, bool tfe, bool ife, bool iis, bool sis, int y_index, int i_index, int t_index, long Ndraw, long Nburn, std::string b_prior, double lambda_b, double c0, double C0, bool geweke, std::string model_sel_optimization);
RcppExport SEXP _BISAM_b_ism_wrapper(SEXP dataSEXP, SEXP include_constantSEXP, SEXP tfeSEXP, SEXP ifeSEXP, SEXP iisSEXP, SEXP sisSEXP, SEXP y_indexSEXP, SEXP i_indexSEXP, SEXP t_indexSEXP, SEXP NdrawSEXP, SEXP NburnSEXP, SEXP b_priorSEXP, SEXP lambda_bSEXP, SEXP c0SEXP, SEXP C0SEXP, SEXP gewekeSEXP, SEXP model_sel_optimizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< bool >::type include_constant(include_constantSEXP);
    Rcpp::traits::input_parameter< bool >::type tfe(tfeSEXP);
    Rcpp::traits::input_parameter< bool >::type ife(ifeSEXP);
    Rcpp::traits::input_parameter< bool >::type iis(iisSEXP);
    Rcpp::traits::input_parameter< bool >::type sis(sisSEXP);
    Rcpp::traits::input_parameter< int >::type y_index(y_indexSEXP);
    Rcpp::traits::input_parameter< int >::type i_index(i_indexSEXP);
    Rcpp::traits::input_parameter< int >::type t_index(t_indexSEXP);
    Rcpp::traits::input_parameter< long >::type Ndraw(NdrawSEXP);
    Rcpp::traits::input_parameter< long >::type Nburn(NburnSEXP);
    Rcpp::traits::input_parameter< std::string >::type b_prior(b_priorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_b(lambda_bSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type C0(C0SEXP);
    Rcpp::traits::input_parameter< bool >::type geweke(gewekeSEXP);
    Rcpp::traits::input_parameter< std::string >::type model_sel_optimization(model_sel_optimizationSEXP);
    rcpp_result_gen = Rcpp::wrap(b_ism_wrapper(data, include_constant, tfe, ife, iis, sis, y_index, i_index, t_index, Ndraw, Nburn, b_prior, lambda_b, c0, C0, geweke, model_sel_optimization));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BISAM_b_ism_wrapper", (DL_FUNC) &_BISAM_b_ism_wrapper, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_BISAM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
