# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

b_ism_wrapper <- function(data, include_constant, tfe, ife, iis, sis, y_index, i_index, t_index, Ndraw, Nburn, b_prior, lambda_b, c0, C0, geweke, tau, va, vb, model_sel_optimization) {
    .Call(`_BISAM_b_ism_wrapper`, data, include_constant, tfe, ife, iis, sis, y_index, i_index, t_index, Ndraw, Nburn, b_prior, lambda_b, c0, C0, geweke, tau, va, vb, model_sel_optimization)
}

rnlp_wrapper <- function(niter, burnin, thinning, y, x, tau, a_phi, b_phi, prior, thini, phiini) {
    .Call(`_BISAM_rnlp_wrapper`, niter, burnin, thinning, y, x, tau, a_phi, b_phi, prior, thini, phiini)
}

model_selection_wrapper <- function(y, x, n_iter, priorCoef, priorDelta, phi, w_i, n_observations, n_timeperiods, optimization_methode) {
    .Call(`_BISAM_model_selection_wrapper`, y, x, n_iter, priorCoef, priorDelta, phi, w_i, n_observations, n_timeperiods, optimization_methode)
}

imomprior <- function(tau, tau_adj = 1e6) {
    .Call(`_BISAM_imomprior`, tau, tau_adj)
}

modelbbprior <- function(alpha_p = 1.0, beta_p = 1.0) {
    .Call(`_BISAM_modelbbprior`, alpha_p, beta_p)
}

igprior <- function(alpha = 1.0, lambda = 1.0) {
    .Call(`_BISAM_igprior`, alpha, lambda)
}

momprior <- function(tau = 1.0, tau_adj = 1e6, r = 1) {
    .Call(`_BISAM_momprior`, tau, tau_adj, r)
}

