# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

b_ism_rcpp <- function(data, i_index, t_index, y_index, Ndraw, Nburn, b_prior, lambda_b, c0, C0, va, vb, tau, geweke, use_phiinit, const_val, ife, tfe, iis, sis) {
    .Call(`_bisam_b_ism_rcpp`, data, i_index, t_index, y_index, Ndraw, Nburn, b_prior, lambda_b, c0, C0, va, vb, tau, geweke, use_phiinit, const_val, ife, tfe, iis, sis)
}

